"""empty message

Revision ID: 3734d99b86e8
Revises: d3fe1c9e365e
Create Date: 2018-04-15 12:32:11.781932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3734d99b86e8'
down_revision = 'd3fe1c9e365e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cards', ['idm'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    # ### end Alembic commands ###
